// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for LarkChatFilterMode.
const (
	All       LarkChatFilterMode = "all"
	Allowlist LarkChatFilterMode = "allowlist"
	Blocklist LarkChatFilterMode = "blocklist"
)

// Valid indicates whether the value is a known member of the LarkChatFilterMode enum.
func (e LarkChatFilterMode) Valid() bool {
	switch e {
	case All:
		return true
	case Allowlist:
		return true
	case Blocklist:
		return true
	default:
		return false
	}
}

// AIClassifyRequest defines model for AIClassifyRequest.
type AIClassifyRequest struct {
	ChatroomIDs []string `json:"chatroom_ids"`
	Date        string   `json:"date"`
}

// AIClassifyResponse defines model for AIClassifyResponse.
type AIClassifyResponse struct {
	Classified int                `json:"classified"`
	OK         bool               `json:"ok"`
	Results    []AIClassifyResult `json:"results"`
}

// AIClassifyResult defines model for AIClassifyResult.
type AIClassifyResult struct {
	Category   string  `json:"category"`
	ChatroomID string  `json:"chatroom_id"`
	Confidence float64 `json:"confidence"`
	Name       string  `json:"name"`
	Reason     string  `json:"reason"`
}

// ActiveGroup defines model for ActiveGroup.
type ActiveGroup struct {
	ChatroomID   string        `json:"chatroom_id"`
	MessageCount int           `json:"message_count"`
	Name         string        `json:"name"`
	SenderCount  int           `json:"sender_count"`
	Summary      string        `json:"summary"`
	TopSenders   []SenderCount `json:"top_senders"`
	Total        int           `json:"total"`
}

// CardsData defines model for CardsData.
type CardsData struct {
	ActiveGroups  int `json:"active_groups"`
	AvgPerGroup   int `json:"avg_per_group"`
	Mentions      int `json:"mentions"`
	SilentGroups  int `json:"silent_groups"`
	TotalGroups   int `json:"total_groups"`
	TotalMessages int `json:"total_messages"`
	UniqueSenders int `json:"unique_senders"`
}

// CategoryInfo defines model for CategoryInfo.
type CategoryInfo struct {
	Color string `json:"color"`
	Emoji string `json:"emoji"`
	ID    int    `json:"id"`
	Name  string `json:"name"`
}

// CategoryStat defines model for CategoryStat.
type CategoryStat struct {
	Category     string `json:"category"`
	Color        string `json:"color"`
	Count        int    `json:"count"`
	Emoji        string `json:"emoji"`
	GroupCount   int    `json:"group_count"`
	ID           int    `json:"id"`
	MessageCount int    `json:"message_count"`
	Name         string `json:"name"`
}

// Config defines model for Config.
type Config struct {
	AutoSyncInterval int            `json:"autoSyncInterval"`
	DefaultRange     string         `json:"defaultRange"`
	DefaultSyncDays  int            `json:"defaultSyncDays"`
	DemoMode         bool           `json:"demoMode"`
	LarkChatFilter   LarkChatFilter `json:"larkChatFilter"`
	LarkCliPath      string         `json:"larkCliPath"`
	MyNicknames      []string       `json:"myNicknames"`
	OpenApiKey       string         `json:"openApiKey"`
	Port             int            `json:"port"`
	PrivacyConfirmed bool           `json:"privacyConfirmed"`
	SetupCompleted   bool           `json:"setupCompleted"`
	Source           string         `json:"source"`
}

// ConfigResponse defines model for ConfigResponse.
type ConfigResponse struct {
	Config Config `json:"config"`
	OK     bool   `json:"ok"`
}

// DailyEntry defines model for DailyEntry.
type DailyEntry struct {
	Date          string `json:"date"`
	MessageCount  int    `json:"message_count"`
	Total         int    `json:"total"`
	UniqueSenders int    `json:"unique_senders"`
}

// DoctorCheck defines model for DoctorCheck.
type DoctorCheck struct {
	Message string `json:"message"`
	Name    string `json:"name"`
	Status  string `json:"status"`
}

// DoctorResponse defines model for DoctorResponse.
type DoctorResponse struct {
	Checks []DoctorCheck `json:"checks"`
	OK     bool          `json:"ok"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
	OK    bool   `json:"ok"`
}

// Favorite defines model for Favorite.
type Favorite struct {
	ChatroomID string  `json:"chatroom_id"`
	Content    string  `json:"content"`
	CreatedAt  *string `json:"created_at,omitempty"`
	Date       string  `json:"date"`
	ID         int     `json:"id"`
	MessageID  string  `json:"message_id"`
	Sender     string  `json:"sender"`
}

// FavoriteToggleRequest defines model for FavoriteToggleRequest.
type FavoriteToggleRequest struct {
	ChatroomID string `json:"chatroom_id"`
	MessageID  string `json:"message_id"`
}

// FavoriteToggleResponse defines model for FavoriteToggleResponse.
type FavoriteToggleResponse struct {
	Favorited bool `json:"favorited"`
	OK        bool `json:"ok"`
}

// FavoritesResponse defines model for FavoritesResponse.
type FavoritesResponse struct {
	Favorites []Favorite `json:"favorites"`
	OK        bool       `json:"ok"`
}

// Group defines model for Group.
type Group struct {
	ChatroomID  string  `json:"chatroom_id"`
	CreatedAt   *string `json:"created_at,omitempty"`
	MemberCount *int    `json:"member_count,omitempty"`
	Name        string  `json:"name"`
}

// GroupDetail Per-session detail used by /api/sessions/{chatroom_id}
type GroupDetail struct {
	ChatroomID   string       `json:"chatroom_id"`
	DailyHistory []DailyEntry `json:"daily_history"`
	Date         string       `json:"date"`
	OK           bool         `json:"ok"`
	Recent       []Message    `json:"recent"`
	Stats        *GroupStats  `json:"stats"`
	SyncState    *SyncState   `json:"sync_state"`
	SyncedDates  []string     `json:"synced_dates"`
}

// GroupDetailResponse Detail used by /api/groups/{chatroom_id} (distinct from GroupDetail)
type GroupDetailResponse struct {
	ChatroomID   string       `json:"chatroom_id"`
	DailyHistory []DailyEntry `json:"daily_history"`
	MemberCount  int          `json:"member_count"`
	Name         string       `json:"name"`
	OK           bool         `json:"ok"`
	Recent       []Message    `json:"recent"`
	Stats        GroupStats   `json:"stats"`
	Tags         []string     `json:"tags"`
}

// GroupStats defines model for GroupStats.
type GroupStats struct {
	ByHour        []HourCount   `json:"by_hour"`
	ByType        []TypeCount   `json:"by_type"`
	Chat          string        `json:"chat"`
	MessageCount  int           `json:"message_count"`
	TopSenders    []SenderCount `json:"top_senders"`
	Total         int           `json:"total"`
	UniqueSenders int           `json:"unique_senders"`
}

// GroupTagRequest defines model for GroupTagRequest.
type GroupTagRequest struct {
	ChatroomID string `json:"chatroom_id"`
	Tag        string `json:"tag"`
}

// GroupTagResponse defines model for GroupTagResponse.
type GroupTagResponse struct {
	OK  bool   `json:"ok"`
	Tag string `json:"tag"`
}

// GroupTagsResponse defines model for GroupTagsResponse.
type GroupTagsResponse struct {
	OK   bool     `json:"ok"`
	Tags []string `json:"tags"`
}

// GroupWithTags defines model for GroupWithTags.
type GroupWithTags struct {
	ChatroomID  string   `json:"chatroom_id"`
	CreatedAt   *string  `json:"created_at,omitempty"`
	MemberCount *int     `json:"member_count,omitempty"`
	Name        string   `json:"name"`
	Tags        []string `json:"tags"`
}

// GroupsResponse defines model for GroupsResponse.
type GroupsResponse struct {
	Groups []GroupWithTags `json:"groups"`
	OK     bool            `json:"ok"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	OK      bool   `json:"ok"`
	Service string `json:"service"`
	Version string `json:"version"`
}

// HourCount defines model for HourCount.
type HourCount struct {
	Count int `json:"count"`
	Hour  int `json:"hour"`
}

// IntelligenceBrief defines model for IntelligenceBrief.
type IntelligenceBrief struct {
	Highlights    []string `json:"highlights"`
	OK            bool     `json:"ok"`
	Opportunities []string `json:"opportunities"`
	Risks         []string `json:"risks"`
	Summary       string   `json:"summary"`
}

// LarkChatFilter defines model for LarkChatFilter.
type LarkChatFilter struct {
	Allowlist []string           `json:"allowlist"`
	Blocklist []string           `json:"blocklist"`
	Mode      LarkChatFilterMode `json:"mode"`
}

// LarkChatFilterMode defines model for LarkChatFilter.Mode.
type LarkChatFilterMode string

// LarkChatItem defines model for LarkChatItem.
type LarkChatItem struct {
	Filtered    bool   `json:"filtered"`
	ID          string `json:"id"`
	MemberCount int    `json:"member_count"`
	Name        string `json:"name"`
}

// LarkChatsResponse defines model for LarkChatsResponse.
type LarkChatsResponse struct {
	Chats  []LarkChatItem `json:"chats"`
	Filter LarkChatFilter `json:"filter"`
	OK     bool           `json:"ok"`
}

// Link defines model for Link.
type Link struct {
	ChatroomID string  `json:"chatroom_id"`
	CreatedAt  *string `json:"created_at,omitempty"`
	Date       string  `json:"date"`
	ID         int     `json:"id"`
	MessageID  string  `json:"message_id"`
	Title      *string `json:"title,omitempty"`
	URL        string  `json:"url"`
}

// LinkAnalyzeRequest defines model for LinkAnalyzeRequest.
type LinkAnalyzeRequest struct {
	ChatroomID string `json:"chatroom_id"`
	Date       string `json:"date"`
}

// LinkAnalyzeResponse defines model for LinkAnalyzeResponse.
type LinkAnalyzeResponse struct {
	Links []Link `json:"links"`
	OK    bool   `json:"ok"`
}

// LinksResponse defines model for LinksResponse.
type LinksResponse struct {
	Links []Link `json:"links"`
	OK    bool   `json:"ok"`
}

// Mention defines model for Mention.
type Mention struct {
	ChatroomID string  `json:"chatroom_id"`
	CreatedAt  *string `json:"created_at,omitempty"`
	Date       string  `json:"date"`
	ID         int     `json:"id"`
	Mentioned  string  `json:"mentioned"`
	Mentioner  string  `json:"mentioner"`
	MessageID  string  `json:"message_id"`
}

// MentionStats defines model for MentionStats.
type MentionStats struct {
	Mentioned   map[string]int      `json:"mentioned"`
	MentionedBy map[string][]string `json:"mentioned_by"`
	OK          bool                `json:"ok"`
}

// MentionsResponse defines model for MentionsResponse.
type MentionsResponse struct {
	Mentions []Mention `json:"mentions"`
	OK       bool      `json:"ok"`
}

// Message defines model for Message.
type Message struct {
	ChatroomID string  `json:"chatroom_id"`
	Content    string  `json:"content"`
	Date       string  `json:"date"`
	LocalID    string  `json:"local_id"`
	Raw        *string `json:"raw,omitempty"`
	Sender     string  `json:"sender"`
	SenderName *string `json:"sender_name,omitempty"`
	Source     string  `json:"source"`
	Time       string  `json:"time"`
	Timestamp  int64   `json:"timestamp"`
	Type       string  `json:"type"`
}

// MessageLink defines model for MessageLink.
type MessageLink struct {
	ChatroomID string  `json:"chatroom_id"`
	CreatedAt  *string `json:"created_at,omitempty"`
	Date       string  `json:"date"`
	ID         int     `json:"id"`
	MessageID  string  `json:"message_id"`
	Resolved   bool    `json:"resolved"`
	Summary    *string `json:"summary,omitempty"`
	Title      *string `json:"title,omitempty"`
	URL        string  `json:"url"`
}

// MessageLinksBackfillResponse defines model for MessageLinksBackfillResponse.
type MessageLinksBackfillResponse struct {
	Inserted int  `json:"inserted"`
	OK       bool `json:"ok"`
}

// MessageLinksRawResponse defines model for MessageLinksRawResponse.
type MessageLinksRawResponse struct {
	Date  string        `json:"date"`
	Links []MessageLink `json:"links"`
	OK    bool          `json:"ok"`
}

// MessageLinksResolveResponse defines model for MessageLinksResolveResponse.
type MessageLinksResolveResponse struct {
	OK       bool `json:"ok"`
	Resolved int  `json:"resolved"`
}

// NewMessagesResponse defines model for NewMessagesResponse.
type NewMessagesResponse struct {
	Count    int       `json:"count"`
	Messages []Message `json:"messages"`
	OK       bool      `json:"ok"`
}

// OKResponse defines model for OKResponse.
type OKResponse struct {
	OK bool `json:"ok"`
}

// ReportRequest defines model for ReportRequest.
type ReportRequest struct {
	ChatroomID string `json:"chatroom_id"`
	Date       string `json:"date"`
	Range      string `json:"range"`
}

// ReportResponse defines model for ReportResponse.
type ReportResponse struct {
	Error  string `json:"error"`
	OK     bool   `json:"ok"`
	Report string `json:"report"`
}

// RescanResponse defines model for RescanResponse.
type RescanResponse struct {
	Message string `json:"message"`
	OK      bool   `json:"ok"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	Count   int            `json:"count"`
	OK      bool           `json:"ok"`
	Results []SearchResult `json:"results"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	ChatName   *string `json:"chat_name,omitempty"`
	ChatroomID string  `json:"chatroom_id"`
	Content    string  `json:"content"`
	Date       string  `json:"date"`
	MessageID  string  `json:"message_id"`
	Sender     string  `json:"sender"`
	Timestamp  int64   `json:"timestamp"`
}

// SenderCount defines model for SenderCount.
type SenderCount struct {
	Count  int    `json:"count"`
	Sender string `json:"sender"`
}

// SessionGroup defines model for SessionGroup.
type SessionGroup struct {
	ChatroomID string `json:"chatroom_id"`
	GroupIDs   []int  `json:"group_ids"`
	IsFavorite bool   `json:"is_favorite"`
	Name       string `json:"name"`
	Summary    string `json:"summary"`
	Time       string `json:"time"`
	Timestamp  int64  `json:"timestamp"`
	Unread     int    `json:"unread"`
}

// SessionsResponse defines model for SessionsResponse.
type SessionsResponse struct {
	Categories []CategoryInfo `json:"categories"`
	Groups     []SessionGroup `json:"groups"`
	OK         bool           `json:"ok"`
	Total      int            `json:"total"`
}

// SetupChecks defines model for SetupChecks.
type SetupChecks struct {
	LarkAuthenticated bool   `json:"larkAuthenticated"`
	LarkError         string `json:"larkError"`
	LarkInstalled     bool   `json:"larkInstalled"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	AutoSyncInterval int            `json:"autoSyncInterval"`
	DefaultRange     string         `json:"defaultRange"`
	DefaultSyncDays  int            `json:"defaultSyncDays"`
	DemoMode         bool           `json:"demoMode"`
	LarkChatFilter   LarkChatFilter `json:"larkChatFilter"`
	LarkCliPath      string         `json:"larkCliPath"`
	MyNicknames      []string       `json:"myNicknames"`
	OpenApiKey       string         `json:"openApiKey"`
	Port             int            `json:"port"`
	PrivacyConfirmed bool           `json:"privacyConfirmed"`
	Source           string         `json:"source"`
}

// SetupResponse defines model for SetupResponse.
type SetupResponse struct {
	Configured bool   `json:"configured"`
	Error      string `json:"error"`
	Message    string `json:"message"`
	OK         bool   `json:"ok"`
}

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	Checks     SetupChecks `json:"checks"`
	Config     Config      `json:"config"`
	Configured bool        `json:"configured"`
	DataDir    string      `json:"dataDir"`
	Error      string      `json:"error"`
	OK         bool        `json:"ok"`
}

// SidebarCounts defines model for SidebarCounts.
type SidebarCounts struct {
	All       int `json:"all"`
	Favorites int `json:"favorites"`
	Unsorted  int `json:"unsorted"`
}

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	ActiveGroups []ActiveGroup  `json:"active_groups"`
	Cards        CardsData      `json:"cards"`
	Categories   []CategoryStat `json:"categories"`

	// Intelligence Free-form intelligence payload (shape varies)
	Intelligence  *map[string]interface{} `json:"intelligence"`
	OK            bool                    `json:"ok"`
	Range         string                  `json:"range"`
	SidebarCounts SidebarCounts           `json:"sidebar_counts"`
	Trend         TrendData               `json:"trend"`
	Window        TimeWindow              `json:"window"`
}

// SyncProgressEvent Payload of an SSE event from /api/lark/sync (stream=1).
type SyncProgressEvent struct {
	ChatID string                `json:"chatId"`
	Count  int                   `json:"count"`
	Error  string                `json:"error"`
	OK     bool                  `json:"ok"`
	Phase  string                `json:"phase"`
	Synced map[string]SyncResult `json:"synced"`

	// Type One of: start, progress, error, finished
	Type string `json:"type"`
}

// SyncProgressSnapshot Best-effort representation of the sync engine status snapshot exposed by /api/sync/progress. Fields depend on the engine.
type SyncProgressSnapshot map[string]interface{}

// SyncRequest defines model for SyncRequest.
type SyncRequest struct {
	// ChatId Sync a single chat. Omit to sync all.
	ChatID   string `json:"chat_id"`
	DaysBack int    `json:"days_back"`
	Stream   bool   `json:"stream"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	Error  string                `json:"error"`
	OK     bool                  `json:"ok"`
	Synced map[string]SyncResult `json:"synced"`
}

// SyncResult defines model for SyncResult.
type SyncResult struct {
	Error    string `json:"error"`
	Inserted int    `json:"inserted"`
	Skipped  int    `json:"skipped"`
}

// SyncState defines model for SyncState.
type SyncState struct {
	ChatroomID    string `json:"chatroom_id"`
	LastSyncedAt  int64  `json:"last_synced_at"`
	Source        string `json:"source"`
	Status        string `json:"status"`
	TotalMessages int    `json:"total_messages"`
}

// TimeWindow defines model for TimeWindow.
type TimeWindow struct {
	Days      int    `json:"days"`
	EndDate   string `json:"end_date"`
	Since     string `json:"since"`
	StartDate string `json:"start_date"`
	Until     string `json:"until"`
}

// Topic defines model for Topic.
type Topic struct {
	Category   string  `json:"category"`
	ChatroomID string  `json:"chatroom_id"`
	Confidence float64 `json:"confidence"`
	CreatedAt  *string `json:"created_at,omitempty"`
	Date       string  `json:"date"`
	ID         int     `json:"id"`
	MessageIDs *string `json:"message_ids,omitempty"`
	Topic      string  `json:"topic"`
}

// TopicAnalyzeRequest defines model for TopicAnalyzeRequest.
type TopicAnalyzeRequest struct {
	ChatroomID string `json:"chatroom_id"`
	Date       string `json:"date"`
}

// TopicAnalyzeResponse defines model for TopicAnalyzeResponse.
type TopicAnalyzeResponse struct {
	OK     bool    `json:"ok"`
	Topics []Topic `json:"topics"`
}

// TopicCategory defines model for TopicCategory.
type TopicCategory struct {
	Category string   `json:"category"`
	Count    int      `json:"count"`
	Topics   *[]Topic `json:"topics,omitempty"`
}

// TopicDetailResponse defines model for TopicDetailResponse.
type TopicDetailResponse struct {
	OK    bool  `json:"ok"`
	Topic Topic `json:"topic"`
}

// TopicLinksResponse defines model for TopicLinksResponse.
type TopicLinksResponse struct {
	Count int     `json:"count"`
	Date  *string `json:"date,omitempty"`
	Links []Link  `json:"links"`
	OK    bool    `json:"ok"`
}

// TopicsResponse defines model for TopicsResponse.
type TopicsResponse struct {
	Categories *[]TopicCategory `json:"categories,omitempty"`
	ChatroomID *string          `json:"chatroom_id,omitempty"`
	Date       *string          `json:"date,omitempty"`
	OK         bool             `json:"ok"`
	Topics     []Topic          `json:"topics"`
}

// TrendData defines model for TrendData.
type TrendData struct {
	Avg    float64      `json:"avg"`
	Data   []TrendPoint `json:"data"`
	Labels []string     `json:"labels"`
	Peak   TrendPoint   `json:"peak"`
	Total  int          `json:"total"`
	Values []int        `json:"values"`
}

// TrendPoint defines model for TrendPoint.
type TrendPoint struct {
	Count int    `json:"count"`
	Date  string `json:"date"`
}

// TypeCount defines model for TypeCount.
type TypeCount struct {
	Count int    `json:"count"`
	Type  string `json:"type"`
}

// WXImageResponse defines model for WXImageResponse.
type WXImageResponse struct {
	Data    string `json:"data"`
	Message string `json:"message"`
	OK      bool   `json:"ok"`
	URL     string `json:"url"`
}

// GetFavoritesParams defines parameters for GetFavorites.
type GetFavoritesParams struct {
	ChatroomID *string `form:"chatroom_id,omitempty" json:"chatroom_id,omitempty"`
}

// DeleteGroupTagParams defines parameters for DeleteGroupTag.
type DeleteGroupTagParams struct {
	ChatroomID string `form:"chatroom_id" json:"chatroom_id"`
	Tag        string `form:"tag" json:"tag"`
}

// GetGroupTagsParams defines parameters for GetGroupTags.
type GetGroupTagsParams struct {
	ChatroomID string `form:"chatroom_id" json:"chatroom_id"`
}

// GetGroupDetailParams defines parameters for GetGroupDetail.
type GetGroupDetailParams struct {
	Date  *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
	Limit *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetIntelligenceParams defines parameters for GetIntelligence.
type GetIntelligenceParams struct {
	Range *string `form:"range,omitempty" json:"range,omitempty"`
}

// GetLarkMessagesParams defines parameters for GetLarkMessages.
type GetLarkMessagesParams struct {
	ChatID string `form:"chat_id" json:"chat_id"`
}

// PostLarkSyncParams defines parameters for PostLarkSync.
type PostLarkSyncParams struct {
	// Stream Set to 'true' or '1' to receive SSE progress events
	Stream *string `form:"stream,omitempty" json:"stream,omitempty"`
}

// GetLinksParams defines parameters for GetLinks.
type GetLinksParams struct {
	ChatroomID *string             `form:"chatroom_id,omitempty" json:"chatroom_id,omitempty"`
	Date       *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// GetMentionsParams defines parameters for GetMentions.
type GetMentionsParams struct {
	ChatroomID *string `form:"chatroom_id,omitempty" json:"chatroom_id,omitempty"`
	Mentioned  *string `form:"mentioned,omitempty" json:"mentioned,omitempty"`
}

// GetMentionStatsParams defines parameters for GetMentionStats.
type GetMentionStatsParams struct {
	ChatroomID *string `form:"chatroom_id,omitempty" json:"chatroom_id,omitempty"`
}

// GetMessageLinksRawParams defines parameters for GetMessageLinksRaw.
type GetMessageLinksRawParams struct {
	Date openapi_types.Date `form:"date" json:"date"`
}

// GetNewMessagesParams defines parameters for GetNewMessages.
type GetNewMessagesParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSearchParams defines parameters for GetSearch.
type GetSearchParams struct {
	Q          string  `form:"q" json:"q"`
	ChatroomID *string `form:"chatroom_id,omitempty" json:"chatroom_id,omitempty"`
	Limit      *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetSessionDetailParams defines parameters for GetSessionDetail.
type GetSessionDetailParams struct {
	Limit *int                `form:"limit,omitempty" json:"limit,omitempty"`
	Date  *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// GetStatsParams defines parameters for GetStats.
type GetStatsParams struct {
	// Range Range key (day/week/month/quarter/year/7d/30d…)
	Range *string `form:"range,omitempty" json:"range,omitempty"`

	// AnchorDate Anchor date for the range, YYYY-MM-DD
	AnchorDate *openapi_types.Date `form:"anchorDate,omitempty" json:"anchorDate,omitempty"`
}

// GetTopicsParams defines parameters for GetTopics.
type GetTopicsParams struct {
	ChatroomID *string             `form:"chatroom_id,omitempty" json:"chatroom_id,omitempty"`
	Date       *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
}

// GetTopicLinksParams defines parameters for GetTopicLinks.
type GetTopicLinksParams struct {
	Date openapi_types.Date `form:"date" json:"date"`
}

// GetWXImageParams defines parameters for GetWXImage.
type GetWXImageParams struct {
	URL string `form:"url" json:"url"`
}

// PostAIClassifyJSONRequestBody defines body for PostAIClassify for application/json ContentType.
type PostAIClassifyJSONRequestBody = AIClassifyRequest

// PostToggleFavoriteJSONRequestBody defines body for PostToggleFavorite for application/json ContentType.
type PostToggleFavoriteJSONRequestBody = FavoriteToggleRequest

// PostGroupTagJSONRequestBody defines body for PostGroupTag for application/json ContentType.
type PostGroupTagJSONRequestBody = GroupTagRequest

// PostLarkSyncJSONRequestBody defines body for PostLarkSync for application/json ContentType.
type PostLarkSyncJSONRequestBody = SyncRequest

// PostAnalyzeLinksJSONRequestBody defines body for PostAnalyzeLinks for application/json ContentType.
type PostAnalyzeLinksJSONRequestBody = LinkAnalyzeRequest

// PostGenerateReportJSONRequestBody defines body for PostGenerateReport for application/json ContentType.
type PostGenerateReportJSONRequestBody = ReportRequest

// PostSetupJSONRequestBody defines body for PostSetup for application/json ContentType.
type PostSetupJSONRequestBody = SetupRequest

// PostSyncJSONRequestBody defines body for PostSync for application/json ContentType.
type PostSyncJSONRequestBody = SyncRequest

// PostAnalyzeTopicsJSONRequestBody defines body for PostAnalyzeTopics for application/json ContentType.
type PostAnalyzeTopicsJSONRequestBody = TopicAnalyzeRequest
